-- STAGING ONLY (project pviqyfnqzcsosihpoxks). Recreates the live schema as it is before Phase 2,
-- with fake data. Never run on the live project.

create extension if not exists pgcrypto with schema extensions;

create table public.users (
  username text primary key, password text not null,
  role text not null check (role = any (array['manager','technician','cashier'])),
  display_name text default '', revoked boolean default false, created_at timestamptz default now());

create table public.customers (
  id bigserial primary key, name text not null, phone text default '', last_seen timestamptz default now());
create unique index customers_name_lower on public.customers (lower(name));

create table public.jobs (
  id bigint primary key, customer_name text not null, device text not null,
  status text default 'received', date_received timestamptz default now(), date_completed timestamptz,
  customer_phone text default '', notes text default '', issue text default '', job_type text default '',
  priority text default 'low', invoice_items text default '', payment text default 'unpaid',
  technician text default 'Unknown', estimated_completion timestamptz,
  inspection text default 'No damage noted', inspection_images text default '',
  claimed_by text default '', claimed_at timestamptz, called_status text default 'not_called',
  called_date timestamptz, called_by text default '', call_notes text default '',
  archived boolean default false, created_at timestamptz default now(), updated_at timestamptz default now());
create index jobs_archived_idx on public.jobs (archived);
create index jobs_status_idx on public.jobs (status);

create table public.job_inspection_images (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  job_id bigint not null references public.jobs(id) on delete cascade,
  image_url text not null, stage text not null default 'check-in', notes text);

create table public.special_orders (
  order_number text primary key, customer text not null, date_requested timestamptz default now(),
  item text not null, quantity integer default 1, status text default 'Pending', notes text default '',
  updated_by text default '', date_updated timestamptz default now(), phone text default '',
  requested_by text default '');

create table public.inventory (
  sku text primary key, name text not null, category text default 'Other', qty integer default 0,
  min_qty integer default 1, cost_price numeric(10,2) default 0, sale_price numeric(10,2) default 0,
  supplier text default '', location text default '', compat text default '', notes text default '',
  last_updated timestamptz default now(), updated_by text default '');

create table public.stock_movements (
  id bigserial primary key, "timestamp" timestamptz default now(),
  sku text not null references public.inventory(sku) on update cascade on delete restrict,
  item_name text default '', type text not null check (type = any (array['add','remove','set'])),
  qty integer not null, qty_before integer default 0, qty_after integer default 0,
  job_id text default '', reason text default '', updated_by text default '');
create index stock_movements_sku_idx on public.stock_movements (sku);

create table public.sales (
  sale_id text primary key, "timestamp" timestamptz default now(), shift_date date, shift text default '',
  cashier text not null, customer text default '', items jsonb not null, total numeric(10,2) not null,
  method text default 'cash', amount_paid numeric(10,2) default 0, job_id text default '',
  status text default 'paid' check (status = any (array['paid','reversed','unpaid','partial','settled'])));
create index sales_cashier_idx on public.sales (cashier);
create index sales_shift_date_idx on public.sales (shift_date);

create table public.payouts (
  payout_id text primary key, "timestamp" timestamptz default now(), shift_date date, shift text default '',
  logged_by text not null, taken_by text default '', amount numeric(10,2) not null, reason text not null);
create index payouts_shift_date_idx on public.payouts (shift_date);

create table public.bills (
  bill_id text primary key, created_at timestamptz default now(), shift_date date, person_name text not null,
  items jsonb not null, total_owed numeric(10,2) default 0, total_paid numeric(10,2) default 0,
  status text default 'open' check (status = any (array['open','settled'])), cashier text default '');

create table public.day_closes (
  close_id text primary key, "timestamp" timestamptz default now(), shift_date date, shift text default '',
  closed_by text not null, gross_sales numeric(10,2) default 0, total_payouts numeric(10,2) default 0,
  net_expected numeric(10,2) default 0, actual_drawer numeric(10,2) default 0,
  variance numeric(10,2) default 0, "float" numeric(10,2) default 0);

create table public.notifications (
  id uuid primary key default gen_random_uuid(), type text not null, title text not null, body text not null,
  "timestamp" timestamptz default now(), delivered_to text[] default '{}');
create index notifications_ts_idx on public.notifications ("timestamp");

create table public.push_subscriptions (
  endpoint text primary key, username text default '', p256dh text not null, auth text not null,
  created_at timestamptz default now());

create table public.audit_log (
  id bigserial primary key, "timestamp" timestamptz default now(), event text not null, actor text not null);

create table public.portal_broadcasts (
  id uuid primary key default gen_random_uuid(), title text not null, message text not null default '',
  variant text not null default 'info' check (variant = any (array['info','warning','urgent'])),
  is_active boolean not null default true, created_by text not null default '',
  created_at timestamptz not null default now());
create index portal_broadcasts_active_idx on public.portal_broadcasts (is_active, created_at desc);
alter table public.portal_broadcasts enable row level security;
create policy portal_broadcasts_select_anon on public.portal_broadcasts for select to anon using (true);
create policy portal_broadcasts_insert_anon on public.portal_broadcasts for insert to anon with check (true);
create policy portal_broadcasts_update_anon on public.portal_broadcasts for update to anon using (true) with check (true);

-- Same as live: every table open to anon (Supabase's default grants), RLS off except broadcasts.
grant all on all tables in schema public to anon, authenticated;
grant all on all sequences in schema public to anon, authenticated;

create or replace function public.track_repair(p_job_id bigint, p_phone4 text)
 returns jsonb language plpgsql security definer set search_path to 'public'
as $function$
declare v_job jobs%rowtype; v_digits text;
begin
  if p_phone4 is null or length(trim(p_phone4)) <> 4 or p_phone4 !~ '^[0-9]{4}$' then
    return jsonb_build_object('success', false, 'authFailed', true);
  end if;
  select * into v_job from jobs where id = p_job_id and coalesce(archived, false) = false;
  if not found then return jsonb_build_object('success', false); end if;
  v_digits := regexp_replace(coalesce(v_job.customer_phone, ''), '[^0-9]', '', 'g');
  if length(v_digits) < 4 or right(v_digits, 4) <> p_phone4 then
    return jsonb_build_object('success', false, 'authFailed', true);
  end if;
  return jsonb_build_object('success', true, 'job', jsonb_build_object(
    'customerName', v_job.customer_name, 'device', v_job.device, 'status', v_job.status,
    'dateReceived', v_job.date_received, 'dateCompleted', v_job.date_completed,
    'estimatedCompletion', v_job.estimated_completion, 'notes', coalesce(v_job.notes, ''),
    'lastUpdated', v_job.updated_at));
end;
$function$;

-- Photo bucket, open like live.
insert into storage.buckets (id, name, public) values ('repair-photos', 'repair-photos', true)
  on conflict (id) do nothing;
create policy "Public Select 6fit35_0"                on storage.objects for select to public using (bucket_id = 'repair-photos');
create policy "Allow public uploads to repair-photos" on storage.objects for insert to public with check (bucket_id = 'repair-photos');
create policy "Allow public updates to repair-photos" on storage.objects for update to public using (bucket_id = 'repair-photos');
create policy "Allow public deletes to repair-photos" on storage.objects for delete to public using (bucket_id = 'repair-photos');

-- ── Fake data ──────────────────────────────────────────────────────────────────────────────
insert into public.users (username, password, role, display_name, revoked) values
  ('Manager_Test',    'test-manager', 'manager',    'Test Manager', false),
  ('Cashier_Test',    'test-cashier', 'cashier',    'Test Cashier', false),
  ('Technician_Test', 'test-tech',    'technician', 'Test Tech',    false),
  ('Technician_Two',  'test-tech2',   'technician', 'Second Tech',  false),
  ('Cashier_Gone',    'test-gone',    'cashier',    'Suspended',    true);

insert into public.customers (name, phone) values ('Fake Customer A', '600-1111'), ('Fake Customer B', '600-2222');

insert into public.jobs (id, customer_name, customer_phone, device, issue, status, technician, claimed_by, claimed_at, payment) values
  (9001, 'Fake Customer A', '600-1111', 'Test Phone X', 'Cracked screen', 'received',    'Technician_Test', '',               null,  'unpaid'),
  (9002, 'Fake Customer B', '600-2222', 'Test Tablet',  'Battery',        'in progress', 'Technician_Two',  'Technician_Two', now(), 'unpaid'),
  (9003, 'Fake Customer A', '600-1111', 'Test Laptop',  'Keyboard',       'ready',       'Technician_Test', 'Technician_Test', now(), 'paid');

insert into public.special_orders (order_number, customer, item, quantity, requested_by) values
  ('SO-1', 'Fake Customer A', 'Test Case', 1, 'Cashier_Test'),
  ('SO-2', 'Fake Customer B', 'Test Charger', 2, 'Manager_Test');

insert into public.inventory (sku, name, category, qty, min_qty, cost_price, sale_price, updated_by) values
  ('TST-001', 'Test Screen Protector', 'Accessories', 20, 5, 2.00, 15.00, 'Manager_Test'),
  ('TST-002', 'Test Battery',          'Parts',        3, 2, 25.00, 80.00, 'Manager_Test');

insert into public.sales (sale_id, shift_date, cashier, customer, items, total, amount_paid) values
  ('S-1000000000001', current_date, 'Cashier_Test', 'Fake Customer A',
   '[{"sku":"TST-001","name":"Test Screen Protector","qty":1,"price":15}]', 15.00, 15.00);

insert into public.audit_log (event, actor) values ('STAGING_SEED', 'setup');
